### ISSUE TITLE
如何取消 key binding 

### ISSUE THREAD

**Issue by Shiwen615** [twtrubiks/linux-note#1]
請問怎麼編輯 Hime 快捷鍵
像是在英文輸入模式時按 ctrl + ? 會產生全形的問號符號
影響使用 IDE 時快捷鍵衝突

**Comment by twtrubiks** [comment]
@Shiwen615 我的只有在中文模式下才會跑出全形. (英文模式下是 全選的功能).
至於有甚麼式可以改這個模式快捷建, 我還真的找不到和 ctrl 有關的, 多數是和 shift 有關, 可能要再找找.

**Comment by Shiwen615** [comment]
ok thx
